version: "3"

services:
  db:
    image: mysql:latest
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=volunteer_test
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  api:
    build: ./api
    container_name: api
    restart: always
    volumes:
      - ./api/:/app
    expose:
      - 9000

  ui:
    build: ./ui
    container_name: ui
    restart: always
    expose:
      - 80

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "8000:8000"
      - "8001:80"

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   restart: always
  #   depends_on:
  #     - db
  #   environment:
  #     - PMA_HOST=db
  #     - MYSQL_ROOT_PASSWORD=root
  #   ports:
  #     - 8080:80
